services:
  rec:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: findme_rec
    restart: always
    environment:
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${QDRANT_PORT}
    ports: 
      - "8050:8050"
    networks:
      - findme-shared-network

networks:
  findme-shared-network:
    external: true
